title: Eucalyptis
author: lypt hub user
email: Kmaile@Keemail.com
description: > # this means to ignore newlines until "baseurl:"
  Trooooooooooooo

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
